# Generated by Django 3.0 on 2019-12-18 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('last_used', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_id', models.CharField(db_index=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('NO MATCHES FOUND', 'No Match')], default='STARTED', max_length=20)),
                ('dna_seq', models.TextField(default='')),
                ('sample_id', models.CharField(max_length=100)),
                ('protein_id', models.CharField(max_length=100)),
                ('protein_pos', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=100, unique=True)),
                ('protein_seq', models.TextField(default='')),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proteinfinder.Samples')),
            ],
        ),
    ]
